<?php

/**
 * BaseLanguages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $code
 * @property string $name
 * @property string $link_url
 * @property string $link_target
 * @property boolean $is_approved
 * @property boolean $is_published
 * @property boolean $is_hidden
 * @property string $parent_language
 * @property integer $parent_id
 * @property string $last_modifier
 * 
 * @method string    getCode()            Returns the current record's "code" value
 * @method string    getName()            Returns the current record's "name" value
 * @method string    getLinkUrl()         Returns the current record's "link_url" value
 * @method string    getLinkTarget()      Returns the current record's "link_target" value
 * @method boolean   getIsApproved()      Returns the current record's "is_approved" value
 * @method boolean   getIsPublished()     Returns the current record's "is_published" value
 * @method boolean   getIsHidden()        Returns the current record's "is_hidden" value
 * @method string    getParentLanguage()  Returns the current record's "parent_language" value
 * @method integer   getParentId()        Returns the current record's "parent_id" value
 * @method string    getLastModifier()    Returns the current record's "last_modifier" value
 * @method Languages setCode()            Sets the current record's "code" value
 * @method Languages setName()            Sets the current record's "name" value
 * @method Languages setLinkUrl()         Sets the current record's "link_url" value
 * @method Languages setLinkTarget()      Sets the current record's "link_target" value
 * @method Languages setIsApproved()      Sets the current record's "is_approved" value
 * @method Languages setIsPublished()     Sets the current record's "is_published" value
 * @method Languages setIsHidden()        Sets the current record's "is_hidden" value
 * @method Languages setParentLanguage()  Sets the current record's "parent_language" value
 * @method Languages setParentId()        Sets the current record's "parent_id" value
 * @method Languages setLastModifier()    Sets the current record's "last_modifier" value
 * 
 * @package    mgto
 * @subpackage model
 * @author     Jeremy and Andy
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLanguages extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('languages');
        $this->hasColumn('code', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('link_url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('link_target', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('is_approved', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('is_published', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('is_hidden', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('parent_language', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('parent_id', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('last_modifier', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}