<?php

/**
 * BaseUserOption
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $option_id
 * @property timestamp $start_date
 * @property timestamp $end_date
 * @property string $last_modifier
 * @property sfGuardUser $sfGuardUser
 * @property VoteOptions $VoteOptions
 * 
 * @method integer     getUserId()        Returns the current record's "user_id" value
 * @method integer     getOptionId()      Returns the current record's "option_id" value
 * @method timestamp   getStartDate()     Returns the current record's "start_date" value
 * @method timestamp   getEndDate()       Returns the current record's "end_date" value
 * @method string      getLastModifier()  Returns the current record's "last_modifier" value
 * @method sfGuardUser getSfGuardUser()   Returns the current record's "sfGuardUser" value
 * @method VoteOptions getVoteOptions()   Returns the current record's "VoteOptions" value
 * @method UserOption  setUserId()        Sets the current record's "user_id" value
 * @method UserOption  setOptionId()      Sets the current record's "option_id" value
 * @method UserOption  setStartDate()     Sets the current record's "start_date" value
 * @method UserOption  setEndDate()       Sets the current record's "end_date" value
 * @method UserOption  setLastModifier()  Sets the current record's "last_modifier" value
 * @method UserOption  setSfGuardUser()   Sets the current record's "sfGuardUser" value
 * @method UserOption  setVoteOptions()   Sets the current record's "VoteOptions" value
 * 
 * @package    mgto
 * @subpackage model
 * @author     Jeremy and Andy
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserOption extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_option');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('option_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('start_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('end_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('last_modifier', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('VoteOptions', array(
             'local' => 'option_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}