<?php

/**
 * BaseBannerGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $banner_width
 * @property string $banner_height
 * @property timestamp $start_date
 * @property timestamp $end_date
 * @property integer $parent_id
 * @property string $last_modifier
 * @property Doctrine_Collection $Banner
 * 
 * @method string              getName()          Returns the current record's "name" value
 * @method string              getBannerWidth()   Returns the current record's "banner_width" value
 * @method string              getBannerHeight()  Returns the current record's "banner_height" value
 * @method timestamp           getStartDate()     Returns the current record's "start_date" value
 * @method timestamp           getEndDate()       Returns the current record's "end_date" value
 * @method integer             getParentId()      Returns the current record's "parent_id" value
 * @method string              getLastModifier()  Returns the current record's "last_modifier" value
 * @method Doctrine_Collection getBanner()        Returns the current record's "Banner" collection
 * @method BannerGroup         setName()          Sets the current record's "name" value
 * @method BannerGroup         setBannerWidth()   Sets the current record's "banner_width" value
 * @method BannerGroup         setBannerHeight()  Sets the current record's "banner_height" value
 * @method BannerGroup         setStartDate()     Sets the current record's "start_date" value
 * @method BannerGroup         setEndDate()       Sets the current record's "end_date" value
 * @method BannerGroup         setParentId()      Sets the current record's "parent_id" value
 * @method BannerGroup         setLastModifier()  Sets the current record's "last_modifier" value
 * @method BannerGroup         setBanner()        Sets the current record's "Banner" collection
 * 
 * @package    mgto
 * @subpackage model
 * @author     Jeremy and Andy
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBannerGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('banner_group');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('banner_width', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('banner_height', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('start_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('end_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('parent_id', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('last_modifier', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Banner', array(
             'local' => 'id',
             'foreign' => 'group_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}