generator:
  class: sfDoctrineGenerator
  param:
    model_class:           StaticContent
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          static_content
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display: [id,_category,title,last_modifier,updated_at]
        max_per_page: 20
        batch_actions:
          _delete:
            credentials:    [delete]
        actions:
          _new: 
            credentials:    [edit, new]
        object_actions:
          _edit:
            credentials:  [edit]
          _delete:
            credentials: [delete]
      filter:  
        display: [category_id]
      form:    ~
      edit:    ~
      new:     ~
