<?php

/**
 * InformationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InformationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InformationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Information');
    }
}