<?php

/**
 * BaseAppIntro
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $company_name
 * @property string $company_logo
 * @property longtext $company_intro
 * @property string $app_name
 * @property longtext $app_intro
 * @property string $app_logo
 * @property string $app_capture
 * @property string $link
 * @property integer $app_id
 * @property string $approve
 * @property string $publish
 * @property boolean $is_hidden
 * @property timestamp $start_date
 * @property timestamp $end_date
 * @property integer $parent_id
 * @property string $last_modifier
 * @property App $App
 * 
 * @method string    getCompanyName()   Returns the current record's "company_name" value
 * @method string    getCompanyLogo()   Returns the current record's "company_logo" value
 * @method longtext  getCompanyIntro()  Returns the current record's "company_intro" value
 * @method string    getAppName()       Returns the current record's "app_name" value
 * @method longtext  getAppIntro()      Returns the current record's "app_intro" value
 * @method string    getAppLogo()       Returns the current record's "app_logo" value
 * @method string    getAppCapture()    Returns the current record's "app_capture" value
 * @method string    getLink()          Returns the current record's "link" value
 * @method integer   getAppId()         Returns the current record's "app_id" value
 * @method string    getApprove()       Returns the current record's "approve" value
 * @method string    getPublish()       Returns the current record's "publish" value
 * @method boolean   getIsHidden()      Returns the current record's "is_hidden" value
 * @method timestamp getStartDate()     Returns the current record's "start_date" value
 * @method timestamp getEndDate()       Returns the current record's "end_date" value
 * @method integer   getParentId()      Returns the current record's "parent_id" value
 * @method string    getLastModifier()  Returns the current record's "last_modifier" value
 * @method App       getApp()           Returns the current record's "App" value
 * @method AppIntro  setCompanyName()   Sets the current record's "company_name" value
 * @method AppIntro  setCompanyLogo()   Sets the current record's "company_logo" value
 * @method AppIntro  setCompanyIntro()  Sets the current record's "company_intro" value
 * @method AppIntro  setAppName()       Sets the current record's "app_name" value
 * @method AppIntro  setAppIntro()      Sets the current record's "app_intro" value
 * @method AppIntro  setAppLogo()       Sets the current record's "app_logo" value
 * @method AppIntro  setAppCapture()    Sets the current record's "app_capture" value
 * @method AppIntro  setLink()          Sets the current record's "link" value
 * @method AppIntro  setAppId()         Sets the current record's "app_id" value
 * @method AppIntro  setApprove()       Sets the current record's "approve" value
 * @method AppIntro  setPublish()       Sets the current record's "publish" value
 * @method AppIntro  setIsHidden()      Sets the current record's "is_hidden" value
 * @method AppIntro  setStartDate()     Sets the current record's "start_date" value
 * @method AppIntro  setEndDate()       Sets the current record's "end_date" value
 * @method AppIntro  setParentId()      Sets the current record's "parent_id" value
 * @method AppIntro  setLastModifier()  Sets the current record's "last_modifier" value
 * @method AppIntro  setApp()           Sets the current record's "App" value
 * 
 * @package    mgto
 * @subpackage model
 * @author     Jeremy and Andy
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAppIntro extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('app_intro');
        $this->hasColumn('company_name', 'string', 145, array(
             'type' => 'string',
             'length' => 145,
             ));
        $this->hasColumn('company_logo', 'string', 245, array(
             'type' => 'string',
             'length' => 245,
             ));
        $this->hasColumn('company_intro', 'longtext', null, array(
             'type' => 'longtext',
             ));
        $this->hasColumn('app_name', 'string', 145, array(
             'type' => 'string',
             'length' => 145,
             ));
        $this->hasColumn('app_intro', 'longtext', null, array(
             'type' => 'longtext',
             ));
        $this->hasColumn('app_logo', 'string', 245, array(
             'type' => 'string',
             'length' => 245,
             ));
        $this->hasColumn('app_capture', 'string', 245, array(
             'type' => 'string',
             'length' => 245,
             ));
        $this->hasColumn('link', 'string', 245, array(
             'type' => 'string',
             'length' => 245,
             ));
        $this->hasColumn('app_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('approve', 'string', 50, array(
             'type' => 'string',
             'default' => 'No',
             'length' => 50,
             ));
        $this->hasColumn('publish', 'string', 50, array(
             'type' => 'string',
             'default' => 'No',
             'length' => 50,
             ));
        $this->hasColumn('is_hidden', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('start_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('end_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('parent_id', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('last_modifier', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('App', array(
             'local' => 'app_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'company_logo',
              1 => 'company_intro',
              2 => 'app_name',
              3 => 'app_intro',
              4 => 'is_hidden',
              5 => 'approve',
              6 => 'publish',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}