<?php

/**
 * ArticleTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArticleTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArticleTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ArticleType');
    }
}