<?php

/**
 * FavoriteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FavoriteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FavoriteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Favorite');
    }
}