<?php

/**
 * ModuleCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModuleCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModuleCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModuleCategory');
    }
}