<?php

/**
 * StatisticalYearTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StatisticalYearTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StatisticalYearTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StatisticalYear');
    }
}