<?php

/**
 * StatisticalYear
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mgto
 * @subpackage model
 * @author     Jeremy and Andy
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class StatisticalYear extends BaseStatisticalYear
{


  public function parentSave(Doctrine_Connection $conn = null){
    return parent::save($conn);
  }
}
