<?php

/**
 * StatisticalMonthTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StatisticalMonthTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StatisticalMonthTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StatisticalMonth');
    }
}