<?php

/**
 * StatisticalDayTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StatisticalDayTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StatisticalDayTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StatisticalDay');
    }
}