<?php

/**
 * ArticleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArticleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArticleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Article');
    }
  public function getPhotoAlbumId($id)
  {
    $q = $this->createQuery('j')
      ->andwhere('j.id = ?',$id);
 
    return $q->fetchOne();
  }
}
