<?php

/**
 * BannerGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BannerGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BannerGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BannerGroup');
    }
}