<?php

/**
 * BaseModule
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $approve
 * @property string $publish
 * @property boolean $is_hidden
 * @property timestamp $start_date
 * @property timestamp $end_date
 * @property integer $parent_id
 * @property string $last_modifier
 * 
 * @method string    getName()          Returns the current record's "name" value
 * @method string    getApprove()       Returns the current record's "approve" value
 * @method string    getPublish()       Returns the current record's "publish" value
 * @method boolean   getIsHidden()      Returns the current record's "is_hidden" value
 * @method timestamp getStartDate()     Returns the current record's "start_date" value
 * @method timestamp getEndDate()       Returns the current record's "end_date" value
 * @method integer   getParentId()      Returns the current record's "parent_id" value
 * @method string    getLastModifier()  Returns the current record's "last_modifier" value
 * @method Module    setName()          Sets the current record's "name" value
 * @method Module    setApprove()       Sets the current record's "approve" value
 * @method Module    setPublish()       Sets the current record's "publish" value
 * @method Module    setIsHidden()      Sets the current record's "is_hidden" value
 * @method Module    setStartDate()     Sets the current record's "start_date" value
 * @method Module    setEndDate()       Sets the current record's "end_date" value
 * @method Module    setParentId()      Sets the current record's "parent_id" value
 * @method Module    setLastModifier()  Sets the current record's "last_modifier" value
 * 
 * @package    mgto
 * @subpackage model
 * @author     Jeremy and Andy
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseModule extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('module');
        $this->hasColumn('name', 'string', 245, array(
             'type' => 'string',
             'length' => 245,
             ));
        $this->hasColumn('approve', 'string', 50, array(
             'type' => 'string',
             'default' => 'No',
             'length' => 50,
             ));
        $this->hasColumn('publish', 'string', 50, array(
             'type' => 'string',
             'default' => 'No',
             'length' => 50,
             ));
        $this->hasColumn('is_hidden', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('start_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('end_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('parent_id', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('last_modifier', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
              1 => 'is_hidden',
              2 => 'approve',
              3 => 'publish',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}