<?php

/**
 * BaseApi
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $public_key
 * @property string $private_key
 * @property string $client
 * @property boolean $is_approved
 * @property boolean $is_published
 * @property boolean $is_hidden
 * @property string $last_modifier
 * 
 * @method string  getPublicKey()     Returns the current record's "public_key" value
 * @method string  getPrivateKey()    Returns the current record's "private_key" value
 * @method string  getClient()        Returns the current record's "client" value
 * @method boolean getIsApproved()    Returns the current record's "is_approved" value
 * @method boolean getIsPublished()   Returns the current record's "is_published" value
 * @method boolean getIsHidden()      Returns the current record's "is_hidden" value
 * @method string  getLastModifier()  Returns the current record's "last_modifier" value
 * @method Api     setPublicKey()     Sets the current record's "public_key" value
 * @method Api     setPrivateKey()    Sets the current record's "private_key" value
 * @method Api     setClient()        Sets the current record's "client" value
 * @method Api     setIsApproved()    Sets the current record's "is_approved" value
 * @method Api     setIsPublished()   Sets the current record's "is_published" value
 * @method Api     setIsHidden()      Sets the current record's "is_hidden" value
 * @method Api     setLastModifier()  Sets the current record's "last_modifier" value
 * 
 * @package    mgto
 * @subpackage model
 * @author     Jeremy and Andy
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseApi extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('api');
        $this->hasColumn('public_key', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('private_key', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('client', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('is_approved', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('is_published', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('is_hidden', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('last_modifier', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}