<?php

/**
 * LanguagesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LanguagesTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object LanguagesTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Languages');
  }

  public function getLanguagesName()
  {
    $types = Doctrine_Core::getTable('MgtoLanguages')->getLanguagesCode();
    return $this->getLanguagesCode() ? $types[$this->getLanguagesCode()] : '';
  }

  public function getLanguagesCode()
  {
	 
    $q = $this->createQuery('l')
      ->limit(20);
	 
    return $q->execute();
  }

  public function getLanguageCodeName()
  {
    $languageCode = $this->createQuery('c')->execute();
    $name = array();
    foreach($languageCode as $lc){
      $name[$lc->getName()] = $lc->getName();
    }
    return $name;
  }
  public function getLanguageCodeId()
  {
    $languageCode = $this->createQuery('c')->execute();
    $name = array();
    foreach($languageCode as $lc){
      $name[$lc->getId()] = $lc->getId();
    }
    return $name;
  }
  public function getLanguageCode()
  {
    $languageCode = $this->createQuery('c')->execute();
    $code = array();
    foreach($languageCode as $lc){
      $code[$lc->getCode()] = $lc->getCode();
    }
    return $code;
  }
  public function findLanguageCode($language)
  {
    $languageCode = $this->createQuery('c')      
      ->where('c.name = ?',$language )->execute();
    $code = '';
    foreach($languageCode as $lc)
      {
        $code= $lc->getCode();
      }
    return $code;
  }



}