generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ArticleType
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          article_type
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:              
        display: [id, module_id, name,last_modifier,updated_at]
        max_per_page: 20
        batch_actions:
          _delete:
            credentials:    [delete]
        actions:
          _new: 
            credentials:    [edit, new]
        object_actions:
          _edit:
            credentials:  [edit]
          _delete:
            credentials: [delete]
      filter:  
        display: [module_id]
      form:    ~
      edit:    ~
      new:     ~
