<?php

/**
 * BaseVoteOptions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $vote_id
 * @property integer $user_id
 * @property string $vote_option
 * @property timestamp $start_date
 * @property timestamp $end_date
 * @property string $last_modifier
 * @property Vote $Vote
 * @property Doctrine_Collection $UserOption
 * 
 * @method integer             getVoteId()        Returns the current record's "vote_id" value
 * @method integer             getUserId()        Returns the current record's "user_id" value
 * @method string              getVoteOption()    Returns the current record's "vote_option" value
 * @method timestamp           getStartDate()     Returns the current record's "start_date" value
 * @method timestamp           getEndDate()       Returns the current record's "end_date" value
 * @method string              getLastModifier()  Returns the current record's "last_modifier" value
 * @method Vote                getVote()          Returns the current record's "Vote" value
 * @method Doctrine_Collection getUserOption()    Returns the current record's "UserOption" collection
 * @method VoteOptions         setVoteId()        Sets the current record's "vote_id" value
 * @method VoteOptions         setUserId()        Sets the current record's "user_id" value
 * @method VoteOptions         setVoteOption()    Sets the current record's "vote_option" value
 * @method VoteOptions         setStartDate()     Sets the current record's "start_date" value
 * @method VoteOptions         setEndDate()       Sets the current record's "end_date" value
 * @method VoteOptions         setLastModifier()  Sets the current record's "last_modifier" value
 * @method VoteOptions         setVote()          Sets the current record's "Vote" value
 * @method VoteOptions         setUserOption()    Sets the current record's "UserOption" collection
 * 
 * @package    mgto
 * @subpackage model
 * @author     Jeremy and Andy
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVoteOptions extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vote_options');
        $this->hasColumn('vote_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('vote_option', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('start_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('end_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('last_modifier', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Vote', array(
             'local' => 'vote_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('UserOption', array(
             'local' => 'id',
             'foreign' => 'option_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'vote_option',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}