<?php

/**
 * StatisticalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StatisticalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StatisticalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Statistical');
    }
}