<?php

/**
 * VoteOptionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VoteOptionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VoteOptionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VoteOptions');
    }
}