<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('mgto_banner', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '45',
             ),
             'image' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'clicks' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'views' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'start_date' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'end_date' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'orders' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'link_url' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'is_hidden' => 
             array(
              'type' => 'bool',
              'length' => '',
             ),
             'parent_language' => 
             array(
              'type' => 'string',
              'length' => '50',
             ),
             'last_modifier' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'MyISAM',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('mgto_banner_group', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '45',
             ),
             'orders' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'link_url' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'is_hidden' => 
             array(
              'type' => 'bool',
              'length' => '',
             ),
             'parent_language' => 
             array(
              'type' => 'string',
              'length' => '50',
             ),
             'last_modifier' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'MyISAM',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('token', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '127',
             ),
             'token_key' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'token_secret' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'expire' => 
             array(
              'type' => 'integer',
              'length' => '11',
             ),
             'params' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'identifier' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'status' => 
             array(
              'type' => 'string',
              'length' => '127',
             ),
             'o_auth_version' => 
             array(
              'type' => 'integer',
              'length' => '2',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('mgto_banner');
        $this->dropTable('mgto_banner_group');
        $this->dropTable('token');
    }
}