<?php

/**
 * BaseBook
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $cover
 * @property longtext $introduction
 * @property string $publisher
 * @property string $translator
 * @property integer $recommended_age
 * @property boolean $daybook
 * @property string $author
 * @property string $drawer
 * @property string $isbn
 * @property string $price
 * @property string $buy_url
 * @property string $approve
 * @property string $publish
 * @property boolean $is_hidden
 * @property timestamp $start_date
 * @property timestamp $end_date
 * @property integer $parent_id
 * @property string $last_modifier
 * @property Doctrine_Collection $Comment
 * 
 * @method string              getName()            Returns the current record's "name" value
 * @method string              getCover()           Returns the current record's "cover" value
 * @method longtext            getIntroduction()    Returns the current record's "introduction" value
 * @method string              getPublisher()       Returns the current record's "publisher" value
 * @method string              getTranslator()      Returns the current record's "translator" value
 * @method integer             getRecommendedAge()  Returns the current record's "recommended_age" value
 * @method boolean             getDaybook()         Returns the current record's "daybook" value
 * @method string              getAuthor()          Returns the current record's "author" value
 * @method string              getDrawer()          Returns the current record's "drawer" value
 * @method string              getIsbn()            Returns the current record's "isbn" value
 * @method string              getPrice()           Returns the current record's "price" value
 * @method string              getBuyUrl()          Returns the current record's "buy_url" value
 * @method string              getApprove()         Returns the current record's "approve" value
 * @method string              getPublish()         Returns the current record's "publish" value
 * @method boolean             getIsHidden()        Returns the current record's "is_hidden" value
 * @method timestamp           getStartDate()       Returns the current record's "start_date" value
 * @method timestamp           getEndDate()         Returns the current record's "end_date" value
 * @method integer             getParentId()        Returns the current record's "parent_id" value
 * @method string              getLastModifier()    Returns the current record's "last_modifier" value
 * @method Doctrine_Collection getComment()         Returns the current record's "Comment" collection
 * @method Book                setName()            Sets the current record's "name" value
 * @method Book                setCover()           Sets the current record's "cover" value
 * @method Book                setIntroduction()    Sets the current record's "introduction" value
 * @method Book                setPublisher()       Sets the current record's "publisher" value
 * @method Book                setTranslator()      Sets the current record's "translator" value
 * @method Book                setRecommendedAge()  Sets the current record's "recommended_age" value
 * @method Book                setDaybook()         Sets the current record's "daybook" value
 * @method Book                setAuthor()          Sets the current record's "author" value
 * @method Book                setDrawer()          Sets the current record's "drawer" value
 * @method Book                setIsbn()            Sets the current record's "isbn" value
 * @method Book                setPrice()           Sets the current record's "price" value
 * @method Book                setBuyUrl()          Sets the current record's "buy_url" value
 * @method Book                setApprove()         Sets the current record's "approve" value
 * @method Book                setPublish()         Sets the current record's "publish" value
 * @method Book                setIsHidden()        Sets the current record's "is_hidden" value
 * @method Book                setStartDate()       Sets the current record's "start_date" value
 * @method Book                setEndDate()         Sets the current record's "end_date" value
 * @method Book                setParentId()        Sets the current record's "parent_id" value
 * @method Book                setLastModifier()    Sets the current record's "last_modifier" value
 * @method Book                setComment()         Sets the current record's "Comment" collection
 * 
 * @package    mgto
 * @subpackage model
 * @author     Jeremy and Andy
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBook extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('book');
        $this->hasColumn('name', 'string', 245, array(
             'type' => 'string',
             'length' => 245,
             ));
        $this->hasColumn('cover', 'string', 245, array(
             'type' => 'string',
             'length' => 245,
             ));
        $this->hasColumn('introduction', 'longtext', null, array(
             'type' => 'longtext',
             ));
        $this->hasColumn('publisher', 'string', 245, array(
             'type' => 'string',
             'length' => 245,
             ));
        $this->hasColumn('translator', 'string', 245, array(
             'type' => 'string',
             'length' => 245,
             ));
        $this->hasColumn('recommended_age', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('daybook', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('author', 'string', 245, array(
             'type' => 'string',
             'length' => 245,
             ));
        $this->hasColumn('drawer', 'string', 245, array(
             'type' => 'string',
             'length' => 245,
             ));
        $this->hasColumn('isbn', 'string', 245, array(
             'type' => 'string',
             'length' => 245,
             ));
        $this->hasColumn('price', 'string', 245, array(
             'type' => 'string',
             'length' => 245,
             ));
        $this->hasColumn('buy_url', 'string', 245, array(
             'type' => 'string',
             'length' => 245,
             ));
        $this->hasColumn('approve', 'string', 50, array(
             'type' => 'string',
             'default' => 'No',
             'length' => 50,
             ));
        $this->hasColumn('publish', 'string', 50, array(
             'type' => 'string',
             'default' => 'No',
             'length' => 50,
             ));
        $this->hasColumn('is_hidden', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('start_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('end_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('parent_id', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('last_modifier', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Comment', array(
             'local' => 'id',
             'foreign' => 'book_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
              1 => 'introduction',
              2 => 'is_hidden',
              3 => 'approve',
              4 => 'publish',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}