<?php

/**
 * ApiTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ApiTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ApiTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Api');
    }
}