<?php

/**
 * BaseStatisticalDay
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $module
 * @property integer $sub_id
 * @property integer $ip_count
 * @property integer $user_count
 * @property integer $visitor_count
 * @property string $last_modifier
 * 
 * @method string         getModule()        Returns the current record's "module" value
 * @method integer        getSubId()         Returns the current record's "sub_id" value
 * @method integer        getIpCount()       Returns the current record's "ip_count" value
 * @method integer        getUserCount()     Returns the current record's "user_count" value
 * @method integer        getVisitorCount()  Returns the current record's "visitor_count" value
 * @method string         getLastModifier()  Returns the current record's "last_modifier" value
 * @method StatisticalDay setModule()        Sets the current record's "module" value
 * @method StatisticalDay setSubId()         Sets the current record's "sub_id" value
 * @method StatisticalDay setIpCount()       Sets the current record's "ip_count" value
 * @method StatisticalDay setUserCount()     Sets the current record's "user_count" value
 * @method StatisticalDay setVisitorCount()  Sets the current record's "visitor_count" value
 * @method StatisticalDay setLastModifier()  Sets the current record's "last_modifier" value
 * 
 * @package    mgto
 * @subpackage model
 * @author     Jeremy and Andy
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStatisticalDay extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('statistical_day');
        $this->hasColumn('module', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('sub_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ip_count', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_count', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('visitor_count', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('last_modifier', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}