<?php

/**
 * BasePhotoAlbum
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $image_one
 * @property string $image_one_description
 * @property string $image_two
 * @property string $image_two_description
 * @property string $image_three
 * @property string $image_three_description
 * @property string $approve
 * @property string $publish
 * @property boolean $is_hidden
 * @property timestamp $start_date
 * @property timestamp $end_date
 * @property integer $parent_id
 * @property string $last_modifier
 * @property Doctrine_Collection $Article
 * @property Doctrine_Collection $Theme
 * 
 * @method string              getName()                    Returns the current record's "name" value
 * @method string              getImageOne()                Returns the current record's "image_one" value
 * @method string              getImageOneDescription()     Returns the current record's "image_one_description" value
 * @method string              getImageTwo()                Returns the current record's "image_two" value
 * @method string              getImageTwoDescription()     Returns the current record's "image_two_description" value
 * @method string              getImageThree()              Returns the current record's "image_three" value
 * @method string              getImageThreeDescription()   Returns the current record's "image_three_description" value
 * @method string              getApprove()                 Returns the current record's "approve" value
 * @method string              getPublish()                 Returns the current record's "publish" value
 * @method boolean             getIsHidden()                Returns the current record's "is_hidden" value
 * @method timestamp           getStartDate()               Returns the current record's "start_date" value
 * @method timestamp           getEndDate()                 Returns the current record's "end_date" value
 * @method integer             getParentId()                Returns the current record's "parent_id" value
 * @method string              getLastModifier()            Returns the current record's "last_modifier" value
 * @method Doctrine_Collection getArticle()                 Returns the current record's "Article" collection
 * @method Doctrine_Collection getTheme()                   Returns the current record's "Theme" collection
 * @method PhotoAlbum          setName()                    Sets the current record's "name" value
 * @method PhotoAlbum          setImageOne()                Sets the current record's "image_one" value
 * @method PhotoAlbum          setImageOneDescription()     Sets the current record's "image_one_description" value
 * @method PhotoAlbum          setImageTwo()                Sets the current record's "image_two" value
 * @method PhotoAlbum          setImageTwoDescription()     Sets the current record's "image_two_description" value
 * @method PhotoAlbum          setImageThree()              Sets the current record's "image_three" value
 * @method PhotoAlbum          setImageThreeDescription()   Sets the current record's "image_three_description" value
 * @method PhotoAlbum          setApprove()                 Sets the current record's "approve" value
 * @method PhotoAlbum          setPublish()                 Sets the current record's "publish" value
 * @method PhotoAlbum          setIsHidden()                Sets the current record's "is_hidden" value
 * @method PhotoAlbum          setStartDate()               Sets the current record's "start_date" value
 * @method PhotoAlbum          setEndDate()                 Sets the current record's "end_date" value
 * @method PhotoAlbum          setParentId()                Sets the current record's "parent_id" value
 * @method PhotoAlbum          setLastModifier()            Sets the current record's "last_modifier" value
 * @method PhotoAlbum          setArticle()                 Sets the current record's "Article" collection
 * @method PhotoAlbum          setTheme()                   Sets the current record's "Theme" collection
 * 
 * @package    mgto
 * @subpackage model
 * @author     Jeremy and Andy
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePhotoAlbum extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('photo_album');
        $this->hasColumn('name', 'string', 245, array(
             'type' => 'string',
             'length' => 245,
             ));
        $this->hasColumn('image_one', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('image_one_description', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
        $this->hasColumn('image_two', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('image_two_description', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
        $this->hasColumn('image_three', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('image_three_description', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
        $this->hasColumn('approve', 'string', 50, array(
             'type' => 'string',
             'default' => 'No',
             'length' => 50,
             ));
        $this->hasColumn('publish', 'string', 50, array(
             'type' => 'string',
             'default' => 'No',
             'length' => 50,
             ));
        $this->hasColumn('is_hidden', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('start_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('end_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('parent_id', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('last_modifier', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Article', array(
             'local' => 'id',
             'foreign' => 'photo_album_id'));

        $this->hasMany('Theme', array(
             'local' => 'id',
             'foreign' => 'photo_album_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
              1 => 'image_one_description',
              2 => 'image_two_description',
              3 => 'image_three_description',
              4 => 'is_hidden',
              5 => 'approve',
              6 => 'publish',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}