<?php

/**
 * BaseFileUpload
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $file_name
 * @property string $file_size
 * @property string $last_modifier
 * @property date $date
 * @property string $remark
 * @property string $path
 * @property string $module
 * @property integer $parent_id
 * @property timestamp $start_date
 * @property timestamp $end_date
 * 
 * @method string     getFileName()      Returns the current record's "file_name" value
 * @method string     getFileSize()      Returns the current record's "file_size" value
 * @method string     getLastModifier()  Returns the current record's "last_modifier" value
 * @method date       getDate()          Returns the current record's "date" value
 * @method string     getRemark()        Returns the current record's "remark" value
 * @method string     getPath()          Returns the current record's "path" value
 * @method string     getModule()        Returns the current record's "module" value
 * @method integer    getParentId()      Returns the current record's "parent_id" value
 * @method timestamp  getStartDate()     Returns the current record's "start_date" value
 * @method timestamp  getEndDate()       Returns the current record's "end_date" value
 * @method FileUpload setFileName()      Sets the current record's "file_name" value
 * @method FileUpload setFileSize()      Sets the current record's "file_size" value
 * @method FileUpload setLastModifier()  Sets the current record's "last_modifier" value
 * @method FileUpload setDate()          Sets the current record's "date" value
 * @method FileUpload setRemark()        Sets the current record's "remark" value
 * @method FileUpload setPath()          Sets the current record's "path" value
 * @method FileUpload setModule()        Sets the current record's "module" value
 * @method FileUpload setParentId()      Sets the current record's "parent_id" value
 * @method FileUpload setStartDate()     Sets the current record's "start_date" value
 * @method FileUpload setEndDate()       Sets the current record's "end_date" value
 * 
 * @package    mgto
 * @subpackage model
 * @author     Jeremy and Andy
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFileUpload extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('file_upload');
        $this->hasColumn('file_name', 'string', 245, array(
             'type' => 'string',
             'length' => 245,
             ));
        $this->hasColumn('file_size', 'string', 245, array(
             'type' => 'string',
             'length' => 245,
             ));
        $this->hasColumn('last_modifier', 'string', 55, array(
             'type' => 'string',
             'length' => 55,
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('remark', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('path', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('module', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('parent_id', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('start_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('end_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}