generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Theme
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          theme
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:             
        display: [id,title,article_link,module_id,last_modifier,updated_at]
        max_per_page: 20
        batch_actions:
          _delete:
            credentials:    [delete]
        actions:
          _new: 
            credentials:    [edit, new]
        object_actions:
          _edit:
            credentials:  [edit]
          _delete:
            credentials: [delete]
      filter:             
        display: [article_link,module_id,photo_album_id]
      form:    ~
      edit:    ~
      new:     ~
