<?php

/**
 * UserOptionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserOptionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserOptionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserOption');
    }
}